// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaZNgS_yZUFgMvy0ivyZHKjTrBr3MZR4c',
    appId: '1:810157677967:web:dfcdcec261c2111ba5bffa',
    messagingSenderId: '810157677967',
    projectId: 'mealsapp-23783',
    authDomain: 'mealsapp-23783.firebaseapp.com',
    storageBucket: 'mealsapp-23783.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpp_NNEyzYfG0qmHSw9vB5RzCAfOIRm-s',
    appId: '1:810157677967:android:be8176b226c29966a5bffa',
    messagingSenderId: '810157677967',
    projectId: 'mealsapp-23783',
    storageBucket: 'mealsapp-23783.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpleCqavGX4O00DBY6htMiVyjSN2lUtDE',
    appId: '1:810157677967:ios:a7b3d524f7c2b294a5bffa',
    messagingSenderId: '810157677967',
    projectId: 'mealsapp-23783',
    storageBucket: 'mealsapp-23783.firebasestorage.app',
    iosBundleId: 'com.example.elBershama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpleCqavGX4O00DBY6htMiVyjSN2lUtDE',
    appId: '1:810157677967:ios:a7b3d524f7c2b294a5bffa',
    messagingSenderId: '810157677967',
    projectId: 'mealsapp-23783',
    storageBucket: 'mealsapp-23783.firebasestorage.app',
    iosBundleId: 'com.example.elBershama',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaZNgS_yZUFgMvy0ivyZHKjTrBr3MZR4c',
    appId: '1:810157677967:web:b1444c5dd25e48fca5bffa',
    messagingSenderId: '810157677967',
    projectId: 'mealsapp-23783',
    authDomain: 'mealsapp-23783.firebaseapp.com',
    storageBucket: 'mealsapp-23783.firebasestorage.app',
  );
}
